# RealEstateAPI Documentation Site Configuration

# Site settings
title: RealEstateAPI Documentation
description: Comprehensive real estate data API with AI-powered features
url: "https://docs.realestateapi.com"
baseurl: ""

# API Version Configuration
api:
  current_version: "v2"
  supported_versions: ["v1", "v2"]
  upcoming_versions: ["v3"]
  deprecated_versions: []
  version_urls:
    v1: "https://api.realestateapi.com/v1"
    v2: "https://api.realestateapi.com/v2"
    v3: "https://api.realestateapi.com/v3"
  
# Navigation structure
navigation:
  main:
    - title: "Getting Started"
      url: "/docs/Documentation/getting-started"
    - title: "API Reference"
      url: "/reference"
      children:
        - title: "AI APIs"
          url: "/reference/AI APIs"
        - title: "Address Standardization"
          url: "/reference/Address Standardization APIs"
        - title: "MLS APIs"
          url: "/reference/MLS APIs"
        - title: "Mapping APIs"
          url: "/reference/Mapping APIs"
        - title: "Property APIs"
          url: "/reference/Property APIs"
        - title: "Property Portfolio APIs"
          url: "/reference/Property Portfolio APIs"
        - title: "Skiptrace APIs"
          url: "/reference/Skiptrace APIs"
        - title: "Utility APIs"
          url: "/reference/Utility APIs"
        - title: "Valuation APIs"
          url: "/reference/Valuation APIs"
        - title: "Response Schemas"
          url : "/reference/Response Schemas"
    - title: "Code Examples"
      url: "/recipes"
    - title: "Integrations"
      url: "/reference/Docs/integrations"
    - title: "Support"
      url: "/support"

# Redirects for legacy URLs
redirects:
  # Default API reference goes to current structure
  - from: "/api-reference"
    to: "/reference"
  - from: "/docs/api-reference"
    to: "/reference"
  - from: "/examples"
    to: "/recipes"
  - from: "/guides"
    to: "/docs/Documentation"
  
  # Legacy version redirects
  - from: "/v1"
    to: "/reference"
  - from: "/v2"
    to: "/reference"
  - from: "/v3"
    to: "/reference"

# Build settings
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed

# Plugins
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed

# Collections for documentation structure
collections:
  reference:
    output: true
    permalink: /reference/:path/
  recipes:
    output: true
    permalink: /recipes/:path/
  docs:
    output: true
    permalink: /docs/:path/

# Default layouts for different content types
defaults:
  - scope:
      path: "reference"
    values:
      layout: "api-docs"
      version: "v2"
      api_url: "https://api.realestateapi.com/v2"
  - scope:
      path: "recipes"
    values:
      layout: "example"
  - scope:
      path: "docs"
    values:
      layout: "documentation"

# Exclude from processing
exclude:
  - node_modules
  - package.json
  - package-lock.json
  - .github
  - .gitignore
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - export.sh