[build]
  publish = "."
  command = "echo 'Static documentation site ready'"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; img-src 'self' data: https:; style-src 'self' 'unsafe-inline'; script-src 'self'"

[[headers]]
  for = "*.md"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/docs/*"
  [headers.values]
    Cache-Control = "public, max-age=1800"

[[redirects]]
  from = "/api-reference/*"
  to = "/docs/api-reference/:splat"
  status = 301

[[redirects]]
  from = "/guide/*"
  to = "/guides/:splat"
  status = 301

[context.production]
  [context.production.environment]
    NODE_ENV = "production"

[context.deploy-preview]
  [context.deploy-preview.environment]
    NODE_ENV = "development"