name: 🐛 Bug Report
description: Report a bug in the documentation or examples
title: "[Bug] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below to help us understand and fix the issue.

  - type: dropdown
    id: area
    attributes:
      label: Area of Issue
      description: Which area of the documentation is affected?
      options:
        - API Reference
        - Code Examples
        - Getting Started Guide
        - Authentication
        - Webhooks
        - Integration Patterns
        - Other
    validations:
      required: true

  - type: input
    id: page
    attributes:
      label: Affected Page/File
      description: Which specific page or file has the issue?
      placeholder: e.g., docs/api-reference/property-search.md
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what happened and what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Follow the example '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here, including screenshots if applicable.

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this issue?
      options:
        - Low - Typo or minor formatting issue
        - Medium - Incorrect information or broken example
        - High - Major functionality doesn't work as documented
    validations:
      required: true