name: ✨ Feature Request
description: Suggest new documentation, examples, or guides
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature for our documentation! Help us understand what would make RealEstateAPI more accessible to developers.

  - type: dropdown
    id: feature_type
    attributes:
      label: Type of Feature
      description: What type of documentation feature are you requesting?
      options:
        - New API endpoint documentation
        - New code example or tutorial
        - New integration guide
        - New language example (e.g., Ruby, Go, etc.)
        - New use case guide
        - Development tool or utility
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem or Use Case
      description: What problem would this feature solve? What use case would it support?
      placeholder: |
        Describe:
        - What developers are trying to accomplish
        - What's currently difficult or missing
        - How this would help the developer community
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: What would you like to see added to the documentation?
      placeholder: |
        Be specific about what you envision:
        - New documentation sections
        - Code examples in specific languages
        - Step-by-step tutorials
        - Integration guides
        - Tools or utilities
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: Examples or References
      description: Are there examples from other APIs or documentation that inspired this request?
      placeholder: |
        Links to:
        - Similar documentation from other APIs
        - Code examples you'd like to see
        - Specific formats or styles you prefer

  - type: dropdown
    id: target_audience
    attributes:
      label: Target Audience
      description: Who would primarily benefit from this feature?
      options:
        - Beginner developers
        - Experienced developers
        - Real estate professionals learning to code
        - Enterprise developers
        - All developers
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority/Impact
      description: How much would this feature impact developer adoption?
      options:
        - Low - Nice to have
        - Medium - Would help many developers
        - High - Critical for developer success
    validations:
      required: true

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Any other context, mockups, or details that might help us understand your request?